name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Change this to your default branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t corydonbaylor/images:flask .  # Replace with your image name

      - name: Push the Docker image
        run: |
          docker push corydonbaylor/images:flask  # Replace with your image name
